export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_FAIL = 'ORDER_GET_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDERS_BYUSER_REQUEST = 'ORDERS_BYUSER_REQUREST'
export const ORDERS_BYUSER_SUCCESS = 'ORDERS_BYUSER_RSUCCESS'
export const ORDERS_BYUSER_FAIL = 'ORDERS_BYUSER_RFAIL'
